Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Template1.Controllers
{
    public class ChatController : Controller
    {
        // GET: Chat
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/EmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Template1.Controllers
{
    public class EmailController : Controller
    {
        // GET: Email
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Update()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Template1.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Template1.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Search()
        {
            return PartialView();
        }
        public ActionResult Update()
        {
            return PartialView();
        }
    }
}

Views/Chat/Index.cshtml
<div class="chat-section">
    <div class="chat-group-selection">
        <div class="chat-selection-header">
            <h5>CHAT</h5>
            <div class="tool-box">
                <div class="tool-item" title="Đánh dấu tất cả đã đọc"><i class="fas fa-check icon"></i></div>
                <div class="tool-item" title="Thêm mới nhóm chat"><i class="fas fa-pen icon"></i></div>
            </div>
        </div>
        <div class="chat-selection-search">
            <div class="chat-search">
                <input placeholder="Keyword" />
                <i class="fas fa-search icon"></i>
            </div>
        </div>
        <div class="chat-selection-body">
            @for (int i = 0; i < 15; i++)
            {
                <div class="chat-selection-item">
                    <div class="avatar" style="background-image: url('../../libs/assets/myavt.jpg');"></div>
                    <strong class="limit-1 m-0">Name of group chat and it long enough for the example</strong>
                    <p class="limit-1 m-0">Sender: <i>This is the last message and it long enough for the example</i></p>
                </div>
            }
        </div>
    </div>
    <div class="chat-box-wrapper">
        <div class="chat-box-header">
            <div class="toggle-chat-selection" id="toggleChatSelection"><i class="fas fa-bars icon"></i></div>
            <div class="chat-title">
                <div class="avatar" style="background-image: url('../../libs/assets/myavt.jpg');"></div>
                <strong class="limit-1 m-0">Name of group chat and it long enough for the example</strong>
                <p class="limit-1 m-0">Promotion title for this group chat. Hope it's some kind of nice word instead of f*ck and p*ss*</p>
            </div>
            <div class="toggle-chat-menu" id="toggleChatMenu"><i class="fas fa-ellipsis-v icon"></i></div>
        </div>
        <div class="chat-box">
            @for (int i = 0; i < 10; i++)
            {
                <div class="chat-item right">
                    <div class="avatar" style="background-image: url('../../libs/assets/myavt.jpg');"></div>
                    <div class="content">
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
                        <strong class="limit-1">@DateTime.Now.ToString("HH:mm dd/MM/yyyy") - Sender</strong>
                    </div>
                </div>
                <div class="chat-item left">
                    <div class="avatar" style="background-image: url('../../libs/assets/myavt.jpg');"></div>
                    <div class="content">
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
                        <strong class="limit-1"> @DateTime.Now.ToString("HH:mm dd/MM/yyyy") - Sender</strong>
                    </div>
                </div>
            }
        </div>
        <div class="chat-box-footer">
            <i class="fas fa-image icon"></i>
            <i class="fas fa-paperclip icon"></i>
            <i class="far fa-grin icon"></i>
            <div class="chat-input">
                <input id="chatMessage" />
                <i class="fas fa-paper-plane icon" id="sendButton"></i>
            </div>
        </div>
    </div>
    <div class="chat-menu">
        <div class="chat-avatar-wrapper picture-selector" onclick="javascript: document.getElementById('image').click()">
            <div id="imagePreview" style="background-image: url('../../libs/assets/myavt.jpg');">
                <div class="layout">
                    <i class="fas fa-edit icon"></i>
                </div>
            </div>
            <input type="file" id="image" />
        </div>
        <div class="chat-menu-group-name">
            <input value="ChatGroup" autocomplete="off" placeholder="Chat group name" />
        </div>
        <div class="chat-menu-item">
            <div class="icon">
                <i class="fas fa-thumbtack"></i>
            </div>
            <div class="text">Pinned message</div>
        </div>
        <div class="chat-menu-item">
            <div class="icon">
                <i class="fas fa-users"></i>
            </div>
            <div class="text">Group members</div>
        </div>
        <div class="chat-menu-item">
            <div class="icon">
                <i class="fas fa-file"></i>
            </div>
            <div class="text">File, image, link,..</div>
        </div>
        <div class="chat-menu-item">
            <div class="icon">
                <i class="fas fa-paint-brush"></i>
            </div>
            <div class="text">Customize group</div>
        </div>
        <div class="chat-menu-item">
            <div class="icon">
                <i class="fas fa-cog"></i>
            </div>
            <div class="text">Personal settings</div>
        </div>
        <div class="chat-menu-item">
            <div class="icon">
                <i class="fas fa-sign-out-alt text-danger"></i>
            </div>
            <div class="text text-danger">Leave group</div>
        </div>
    </div>
</div>
<script src="~/Scripts/ChatIndex.js"></script>

Views/Home/Login.cshtml
@{ 
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Template 1</title>
    <link href="~/libs/lib.css" rel="stylesheet" />
    <link href="~/libs/rlib.css" rel="stylesheet" />
    <script src="~/libs/jquery.js"></script>
    <script src="~/libs/lib.js"></script>
    <link href="~/libs/css/style.css" rel="stylesheet" />
    <link href="~/libs/css/darkmode.css" rel="stylesheet" />
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center center;
            background-image: url('../../libs/assets/light-trails-buildings.jpg');
        }
        .login-layout {
            width:100%;
            max-width:500px;
            padding:15px;
            border-radius:0.5rem;
            background:rgba(255,255,255,0.8);
        }
        .r-form-item.focus input ~ label {
            border:1px solid #004dd1;
            box-shadow:#004dd1 0px 0px 3px;
            border-radius:0.2rem;
        }
    </style>
</head>
<body>
    <div class="login-layout">
        <form>
            <div class="r-form-item">
                <input />
                <label>Username</label>
            </div>
            <div class="r-form-item">
                <input />
                <label>Password</label>
            </div>
            <div class="row mt-3">
                <div class="col-lg-12 text-center">
                    <button class="rbtn rbtn-success">Login</button>
                </div>
            </div>
        </form>
    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Template 1</title>
    <link href="~/libs/lib.css" rel="stylesheet" />
    <link href="~/libs/rlib.css" rel="stylesheet" />
    <script src="~/libs/jquery.js"></script>
    <script src="~/libs/lib.js"></script>
    <link href="~/libs/css/style.css" rel="stylesheet" />
    <link href="~/libs/css/darkmode.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
    <script src="~/signalr/hubs"></script>
</head>
<body>
    <header>
        <div class="title">
            <h4>TEMPLATE HEADER 1</h4>
        </div>
        <div class="header-profile">
            <i class="far fa-moon icon"></i>
            <i class="far fa-envelope icon"></i>
            <i class="far fa-bell icon"></i>
            <i class="fas fa-cog icon"></i>
            <img src="~/libs/assets/myavt.jpg" />
        </div>
    </header>
    <div class="left-menu">
        <div class="menu-item">
            <div class="menu-header">
                <div class="icon">
                    <i class="fas fa-home"></i>
                </div>
                <div class="text">
                    <p class="limit-1">Home Page</p>
                </div>
            </div>
        </div>
        <div class="menu-item user">
            <div class="menu-header">
                <div class="icon">
                    <i class="fas fa-users"></i>
                </div>
                <div class="text">
                    <p class="limit-1">Users</p>
                </div>
            </div>
        </div>
        <div class="menu-item has-child email-received email-sent email-draft email-trash email-new">
            <div class="menu-header">
                <div class="icon">
                    <i class="fas fa-envelope-open-text"></i>
                </div>
                <div class="text">
                    <p class="limit-1">Email</p>
                </div>
            </div>
            <div class="menu-child">
                <a class="limit-1 email-new" href="@Url.Action("Update", "Email")">New email</a>
                <a class="limit-1 email-received" href="@Url.Action("Index", "Email")">Received</a>
                <a class="limit-1 email-sent">Sent</a>
                <a class="limit-1 email-draft">Draft</a>
                <a class="limit-1 email-trash">Trash</a>
            </div>
        </div>
        <div class="menu-item chats" onclick="javascript: window.location.href = '@Url.Action("Index", "Chat")'">
            <div class="menu-header">
                <div class="icon">
                    <i class="fas fa-comment"></i>
                </div>
                <div class="text">
                    <p class="limit-1">Chats</p>
                </div>
            </div>
        </div>
        <div class="menu-item has-child">
            <div class="menu-header">
                <div class="icon">
                    <i class="fas fa-cogs"></i>
                </div>
                <div class="text">
                    <p class="limit-1">Settings</p>
                </div>
            </div>
            <div class="menu-child">
                <a class="limit-1">Set Permission</a>
                <a class="limit-1">System Settings</a>
            </div>
        </div>
    </div>
    <div class="main-content">
        @RenderBody()
    </div>
    <footer>
        <p class="m-0">Copyright &copy; RoZ @DateTime.Now.Year</p>
    </footer>
    <div class="side-bar"></div>
    <div class="r-modal-wrapper" onclick="RModalHide()">
        <div class="r-modal"></div>
    </div>
</body>
</html>

Views/User/Index.cshtml
<div class="content-header">
    <div class="row">
        <div class="col-lg-4">
            <h4>USER TABLE</h4>
        </div>
        <div class="col-lg-4 d-flex justify-content-center">
            <b>TOTAL: 10</b>
        </div>
        <div class="col-lg-4 tool-bar d-flex justify-content-end align-items-center">
            <div class="amount-row-selection">
                <div class="r-form-item m-0">
                    <select>
                        <option value="5">5</option>
                        <option value="10" selected>10</option>
                        <option value="20">20</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select>
                    <label>Row amount</label>
                </div>
            </div>
            <i class="fas fa-plus icon" onclick="RModalShow('@Url.Action("Update", "User")')"></i>
            <i class="fas fa-search icon" onclick="OpenSidebar('@Url.Action("Search", "User")')"></i>
        </div>
    </div>
</div>
<table class="r-table-1">
    <thead>
        <tr>
            <th width="80">INDEX</th>
            <th>USERNAME</th>
            <th>EMAIL</th>
            <th>PHONE</th>
            <th>ADDRESS</th>
            <th width="150">ACTION</th>
        </tr>
    </thead>
    <tbody>
        @for(int i = 0; i < 30;i++)
            {
                <tr>
                    <td class="text-center">@(i+1)</td>
                    <td>username@(i+1)</td>
                    <td class="text-center">email@(i+1)@@gmail.com</td>
                    <td class="text-center">09@(i)254179</td>
                    <td>address@(i+1)</td>
                    <td class="text-center">
                        <button class="rbtn rbtn-warning"><i class="fas fa-pen"></i></button>
                        <button class="rbtn rbtn-danger"><i class="fas fa-trash-alt"></i></button>
                        <button class="rbtn rbtn-secondary"><i class="fas fa-lock"></i></button>
                    </td>
                </tr>
            }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="99">
                <div class="page-nav-wrapper">
                    <div class="page-nav">
                        <div class="nav-btn"><i class="fas fa-angle-double-left icon"></i></div>
                        <div class="nav-btn"><i class="fas fa-angle-left icon"></i></div>
                        <div class="nav-input"><input value="1" /> / <span>1</span></div>
                        <div class="nav-btn"><i class="fas fa-angle-right icon"></i></div>
                        <div class="nav-btn"><i class="fas fa-angle-double-right icon"></i></div>
                    </div>
                </div>
            </td>
        </tr>
    </tfoot>
</table>
<script>
    rActive = "user"
</script>

Views/User/Search.cshtml
<div class="side-bar-header">
    <h4 class="limit-1">SEARCH USER</h4>
    <i class="fas fa-times close-icon" onclick="CloseSidebar()"></i>
</div>
<div class="side-bar-body">
    <div class="r-form-item">
        <input />
        <label>Keyword</label>
    </div>
</div>
<div class="side-bar-footer">
    <button class="rbtn rbtn-success">Search</button>
    <button class="rbtn rbtn-secondary" onclick="CloseSidebar()">Close</button>
</div>

Views/User/Update.cshtml
<div class="r-modal-header">
    <h4>CREATE NEW USER</h4>
    <i class="fas fa-times close-icon" onclick="RModalHide()"></i>
</div>
<form class="r-form">
    <div class="r-modal-body">
        <div class="r-form-item">
            <input req="text" />
            <label>Username</label>
        </div>
        <div class="r-form-item">
            <input req="text" type="password" />
            <label>Password</label>
        </div>
        <div class="r-form-item">
            <input req="text" />
            <label>Email</label>
        </div>
        <div class="r-form-item">
            <input req="num" />
            <label>Phone number</label>
        </div>
        <div class="r-form-item">
            <textarea></textarea>
            <label>Notes</label>
        </div>
    </div>
    <div class="r-modal-footer">
        <button class="rbtn rbtn-success">Create</button>
        <button class="rbtn rbtn-secondary" onclick="RModalHide()">Close</button>
    </div>
</form>